services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      - RDS_HOSTNAME
      - RDS_DB_NAME
      - RDS_PASSWORD
      - RDS_HOST
      - RDS_PORT
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - RDS_HOSTNAME
      - RDS_DB_NAME
      - RDS_PASSWORD
      - RDS_HOST
      - RDS_PORT