version: '3'
services:
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      - RDS_DB_NAME
      - RDS_USERNAME
      - RDS_PASSWORD
      - RDS_HOSTNAME
      - RDS_PORT
      - POSTGRES_HOST_AUTH_METHOD=trust

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - RDS_DB_NAME
      - RDS_USERNAME
      - RDS_PASSWORD
      - DJANGO_SETTINGS_MODULE=app.settings
      - RANDOM_V4_API_URL
      - RANDOM_API_KEY
    depends_on:
      - db

volumes:
  db_data: