branch-defaults:
  main:
    environment: the-man-who-calculated-be-dev
    group_suffix: null
environment-defaults:
  the-man-who-calculated-be-dev:
    branch: main
    repository: origin
global:
  application_name: the-man-who-calculated-be
  branch: main
  default_ec2_keyname: truenorth django app
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: origin
  sc: git
  workspace_type: Application
