# Generated by Django 3.2.19 on 2023-06-22 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='token generated by auth.tokens library using the secret key stored on settings.py', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date the token was created')),
                ('expires_at', models.DateTimeField(help_text='Datetime the token will expire', null=True)),
                ('deleted', models.BooleanField(default=False, help_text='For logical deletion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.user')),
            ],
        ),
    ]
