# Generated by Django 3.2.19 on 2023-06-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='deleted',
            field=models.BooleanField(default=False, help_text='For logical deletion'),
        ),
    ]
