# Generated by Django 3.2.19 on 2023-06-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_record_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='fields',
            field=models.JSONField(default=dict, help_text='Store required fields to perform the operation'),
        ),
    ]
